import { execSync } from "child_process";
import path from "path";
import fs from "fs/promises";
import { type MobileApp } from "@/modules/mobile-builder/types/mobile.types";
import { runCommand } from "@/modules/mobile-builder/utils/env-detection";

export interface CapacitorConfig {
  appId: string;
  appName: string;
  webDir: string;
  server: { url: string };
  plugins: Record<string, unknown>;
  android: { compileSdkVersion: number; targetSdkVersion: number };
}

export class CapacitorService {
  private app: MobileApp;
  private projectRoot: string;

  constructor(app: MobileApp) {
    this.app = app;
    this.projectRoot = path.join(process.cwd(), "mobile-build", app.slug);
  }

  async initialize(): Promise<void> {
    await fs.mkdir(this.projectRoot, { recursive: true });
    await this.copyWebApp();
    await this.generateConfig();
  }

  private async copyWebApp(): Promise<void> {
    const webDir = path.join(this.projectRoot, "web-build");
    await fs.mkdir(webDir, { recursive: true });

    execSync(`npx cap copy --asset-dir ${this.app.repositoryUrl}`, {
      cwd: this.projectRoot,
      stdio: "pipe",
    });
  }

  private async generateConfig(): Promise<void> {
    const config: CapacitorConfig = {
      appId: this.app.packageName,
      appName: this.app.name,
      webDir: "web-build",
      server: { url: "http://10.0.2.2:3000" },
      plugins: {
        SplashScreen: {
          launchShowDuration: 0,
        },
        StatusBar: {
          style: "LIGHT",
        },
      },
      android: {
        compileSdkVersion: this.getCompileSdk(),
        targetSdkVersion: this.getTargetSdk(),
      },
    };

    await this.writeCapacitorConfig(config);
  }

  private getCompileSdk(): number {
    return 34;
  }

  private getTargetSdk(): number {
    return 34;
  }

  private async writeCapacitorConfig(config: CapacitorConfig): Promise<void> {
    const configContent = `// Auto-generated by Mobile App Builder
import { defineConfig } from '@capacitor/cli';

export default defineConfig({
  appId: '${config.appId}',
  appName: '${config.appName}',
  webDir: '${config.webDir}',
  server: ${JSON.stringify(config.server, null, 2)},
  plugins: ${JSON.stringify(config.plugins, null, 2)},
  android: ${JSON.stringify(config.android, null, 2)},
});
`;

    await fs.writeFile(path.join(this.projectRoot, "capacitor.config.ts"), configContent);
  }

  async addAndroid(): Promise<void> {
    const result = await runCommand("npx cap add android", { timeout: 120000 });
    if (!result.success) {
      throw new Error(`Failed to add Android platform: ${result.error || result.output}`);
    }
  }

  async addIos(): Promise<void> {
    const result = await runCommand("npx cap add ios", { timeout: 120000 });
    if (!result.success) {
      throw new Error(`Failed to add iOS platform: ${result.error || result.output}`);
    }
  }

  async sync(platform: "android" | "ios"): Promise<void> {
    const result = await runCommand(`npx cap sync ${platform}`, { timeout: 120000 });
    if (!result.success) {
      throw new Error(`Failed to sync ${platform}: ${result.error || result.output}`);
    }
  }

  async open(platform: "android" | "ios"): Promise<void> {
    const result = await runCommand(`npx cap open ${platform}`, { timeout: 30000 });
    if (!result.success) {
      throw new Error(`Failed to open ${platform}: ${result.error || result.output}`);
    }
  }

  getProjectRoot(): string {
    return this.projectRoot;
  }

  getAndroidProjectPath(): string {
    return path.join(this.projectRoot, "android");
  }

  getIosProjectPath(): string {
    return path.join(this.projectRoot, "ios");
  }
}
